baseURL = 'https://hydroakri.github.io/'
languageCode = 'zh-cn'
title = "Hydroakri's Blog"
theme = "PaperMod"
publishDir = 'docs'
paginate = '5'

[menu]
 
 [[menu.main]]
      identifier = 'Tags'
      name = 'Tags'
      url = '/Tags/'
      weight = '20'

[[menu.main]]
      identifier = 'archives'
      name = 'Archives'
      url = 'archives'
      weight = '20'

 

[params]
    [params.homeInfoParams]
        Title = 'Hey there'
        Content = '为何一切尚未消失？'

    [socialIcons]
            name = 'github'
            url = "https://github.com/adityatelange/hugo-PaperMod"
